In [24]:
import pandas as pd
import numpy as np

ref_system = pd.read_csv("D:/Santai Coding/Pradigma - Digital Maintenance Portal/Data Migration/SAP Integration/SHAREPOINT/sharepoint_system.csv")
ref_sub_system = pd.read_csv("D:/Santai Coding/Pradigma - Digital Maintenance Portal/Data Migration/SAP Integration/SHAREPOINT/sharepoint_sub_system.csv")
ref_sub_sub_system = pd.read_csv("D:/Santai Coding/Pradigma - Digital Maintenance Portal/Data Migration/SAP Integration/SHAREPOINT/sharepoint_sub_sub_system.csv")
ref_root_cause = pd.read_csv("D:/Santai Coding/Pradigma - Digital Maintenance Portal/Data Migration/SAP Integration/SHAREPOINT/sharepoint_root_cause.csv")

ref_system_hierarchy = pd.read_csv("D:/Santai Coding/Pradigma - Digital Maintenance Portal/Data Migration/SAP Integration/SHAREPOINT/sharepoint_system_hierarchy.csv")

### RSD

In [25]:
dept = "Rolling Stock Department"

system_rsd = ref_system[ref_system['department'] == dept].copy()
sub_system_rsd = ref_sub_system[ref_sub_system['department'] == dept].copy()
sub_sub_system_rsd = ref_sub_sub_system[ref_sub_sub_system['department'] == dept].copy()
root_cause_rsd = ref_root_cause[ref_root_cause['department'] == dept].copy()
system_hierarchy_rsd = ref_system_hierarchy[ref_system_hierarchy['department'] == dept].copy()

In [26]:
system_map = system_rsd.set_index('system')['ID']
sub_system_map = sub_system_rsd.set_index('sub_system')['ID']
sub_sub_system_map = sub_sub_system_rsd.set_index('sub_sub_system')['ID']
root_cause_map = root_cause_rsd.set_index('root_cause')['ID']

system_hierarchy_rsd['system_id'] = system_hierarchy_rsd['system'].map(system_map)
system_hierarchy_rsd['sub_system_id'] = system_hierarchy_rsd['sub_system'].map(sub_system_map)
system_hierarchy_rsd['sub_sub_system_id'] = system_hierarchy_rsd['sub_sub_system'].map(sub_sub_system_map)
system_hierarchy_rsd['root_cause_id'] = system_hierarchy_rsd['root_cause'].map(root_cause_map)

system_hierarchy_rsd.head()

,ID,system,sub_system,sub_sub_system,root_cause,department,Modified,system_id,sub_system_id,sub_sub_system_id,root_cause_id
3962,3963,Not Applicable,Auxiliary Power System (APS),Not Applicable,Reslot connector CN2DN,Rolling Stock Department,5/6/2026 3:31 AM,1,74.0,NaN,187
3963,3964,Not Applicable,Auxiliary Power System (APS),Not Applicable,Device Net Connector problem,Rolling Stock Department,5/6/2026 3:31 AM,1,74.0,NaN,188
3964,3965,Not Applicable,Auxiliary Power System (APS),Not Applicable,Cable Loose,Rolling Stock Department,5/6/2026 3:31 AM,1,74.0,NaN,88
3965,3966,Not Applicable,Auxiliary Power System (APS),Not Applicable,UOF,Rolling Stock Department,5/6/2026 3:31 AM,1,74.0,NaN,189
3966,3967,Not Applicable,Auxiliary Power System (APS),Not Applicable,Reslot anybus,Rolling Stock Department,5/6/2026 3:31 AM,1,74.0,NaN,190

### PSD

In [27]:
ref_system_hierarchy

,ID,system,sub_system,sub_sub_system,root_cause,department,Modified
0,1,Generator Set,Volvo 100kVa,AMF Board,"Relay, Timer, loose connection, Under voltage ...",Power System Department,5/5/2026 5:10 PM
1,2,Generator Set,Volvo 100kVa,Engine,"Engine oil, filter & Coolant leak",Power System Department,5/5/2026 5:10 PM
2,3,Generator Set,Volvo 100kVa,Alternator,Insulation is cracked or brittle,Power System Department,5/5/2026 5:10 PM
3,4,Generator Set,Volvo 100kVa,Battery,"Charger card failure, power supply failure, Ba...",Power System Department,5/5/2026 5:10 PM
4,5,Generator Set,Volvo 175kVa,AMF Board,"Relay, Timer, loose connection, Under voltage ...",Power System Department,5/5/2026 5:10 PM
...,...,...,...,...,...,...,...
4982,4983,Automatic Train Wash Plant,"Horizontal cylinder, bearing",Carriage left,Not Applicable,Track Network Maintenance Department,5/6/2026 3:33 AM
4983,4984,Automatic Train Wash Plant,"Horizontal cylinder, bearing",Cable guiding castor complete,Not Applicable,Track Network Maintenance Department,5/6/2026 3:33 AM
4984,4985,Automatic Train Wash Plant,Driving device for lateral cylinders,"Full Brush Shell 300 X 500 mm Dense, Over Length",Not Applicable,Track Network Maintenance Department,5/6/2026 3:33 AM
4985,4986,Automatic Train Wash Plant,Driving device for lateral cylinders,"Full brush shell 300 x 450 mm dense, over length,",Not Applicable,Track Network Maintenance Department,5/6/2026 3:33 AM
4986,4987,Automatic Train Wash Plant,Driving device for lateral cylinders,"Full Brush Shell 300 X 450 mm Dense, Over Length",Not Applicable,Track Network Maintenance Department,5/6/2026 3:33 AM